apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azureblob
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: blob1
    volumeAttributes:
      containerName: myblobcontainer
      storageAccount: mystoreaccountparthiv
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
