apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azureblob
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-fuse-premium
  resources:
    requests:
      storage: 5Gi
